# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NWthADLozOFu_37N1kDCZ0K4yPu6js-s
"""

m=[[1,'a',['cat'],2],[[[3]],'dog'],4,5]
new_m=[]
def flatten(lst):
    for item in lst:
        if  isinstance(item, list):
         flatten(item)
        else:
            new_m.append(item)

flatten(m)
print(new_m)

a=[[1, 2], [3, 4], [5, 6, 7]]

def reverse(lst):
  reversed_a=[]
  for item in reversed(lst):
    if isinstance(item,list):
       reversed_a.append(reverse(item))
    else:
       reversed_a.append(item)
  return reversed_a

print(reverse(a))